monster:
    image: qnib/monster
    ports:
    - "8500:8500"
    - "9200:9200"
    - "80:80"
    - "8080:8080"
    - "8088:8088"
    - "2003:2003"
    - "5601:5601"
    - "8125/udp:8125/udp"
    environment:
    - DC_NAME=dc1
    - CNT_TYPE=service
    - FORWARD_TO_LOGSTASH=true
    hostname: monster
    dns: 127.0.0.1
    privileged: true
    volumes:
    - "/var/lib/carbon/whisper/"
    - "/var/lib/elasticsearch/"
    - "./etc/nginx/conf.d/:/etc/nginx/conf.d/"
